### PR TITLE
PAE-124.1 - Removing gradebook.html template.

### PR DESCRIPTION
**Pull request by Squirrel18**
## Description:

This PR removes the changes made at https://github.com/proversity-org/proversity-openedx-themes/pull/275 as enrolled users will now be filtered at the backend level.

## Note:

The template was completely removed.

## Reviewers:

- [ ] @andrey-canon 
- [ ] @diegomillan

### CODE REVIEW

**Review by diegomillan — APPROVED** [review]

**Comment by andrey-canon** [comment]
@Squirrel18  if the template doesn't have any changes you can leave it out

**Comment by Squirrel18** [comment]
Maybe we need it in the short future and then we have to added it again if not, let's mark it as a template to remove for the next migration. makes sense? @andrey-canon

**Comment by andrey-canon** [comment]
@Squirrel18  imo unless you have a specific situation where it can be useful, we shouldn't keep it, since we didn't need this before

**Comment by Squirrel18** [comment]
Anyway, removed... @andrey-canon

**Review by andrey-canon — APPROVED** [review]

**Pull request merged**
